# Generated by Django 3.2 on 2021-07-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0002_bid_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='photos',
            field=models.ImageField(upload_to='bids/%Y/%m/%d'),
        ),
    ]
