# Generated by Django 3.2 on 2021-07-21 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0003_alter_bid_photos'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_participants', models.ImageField(upload_to='bids/photo_participants/%Y/%m/%d', verbose_name='Фото участников')),
                ('photo_alcohol', models.ImageField(upload_to='bids/photo_alcohol/%Y/%m/%d', verbose_name='Фото алкоголя')),
            ],
        ),
        migrations.AlterField(
            model_name='bid',
            name='photos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bid.bidimages', verbose_name='Фотографии'),
        ),
    ]
