# Generated by Django 3.2 on 2021-07-21 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0004_auto_20210721_0817'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bidimages',
            options={'verbose_name': 'Фотография', 'verbose_name_plural': 'Фотографии'},
        ),
    ]
