# Generated by Django 3.2 on 2021-07-22 08:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_birth_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 22, 8, 8, 3, 22178, tzinfo=utc)),
        ),
    ]
