# Generated by Django 3.2 on 2021-07-23 05:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_last_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 23, 5, 49, 25, 361400, tzinfo=utc), verbose_name='Последний раз в сети'),
        ),
    ]
