# Generated by Django 3.2 on 2021-07-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-date'], 'verbose_name': 'Сообщение чата', 'verbose_name_plural': 'Сообщения чатов'},
        ),
        migrations.AlterField(
            model_name='chat',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата отправки'),
        ),
    ]
