# Generated by Django 3.2 on 2021-07-24 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0002_participant_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_participants', models.ImageField(upload_to='participant/photo_participants/%Y/%m/%d', verbose_name='Фото участников')),
                ('photo_alcohol', models.ImageField(upload_to='participant/photo_alcohol/%Y/%m/%d', verbose_name='Фото алкоголя')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.AlterField(
            model_name='participant',
            name='photos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participant.participantimages', verbose_name='Фотографии'),
        ),
    ]
